import java.util.zip.ZipEntry
import java.util.zip.ZipInputStream

plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.4'
	id 'io.spring.dependency-management' version '1.1.6'
}

group = 'eu.foobarsgamessmithy'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

ext {
	mapstructVersion = "1.6.0"
	lombokVersion = "1.18.30"
	lombokMapstructBindingVersion = "0.2.0"
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-web'

	implementation "org.mapstruct:mapstruct:${mapstructVersion}", "org.projectlombok:lombok:${lombokVersion}"
	annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}", "org.projectlombok:lombok:${lombokVersion}", "org.projectlombok:lombok-mapstruct-binding:${lombokMapstructBindingVersion}"

	runtimeOnly 'com.h2database:h2:2.3.232'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}

class KeycloakTask extends DefaultTask {
	@TaskAction
	void action() {
		downloadAndUnzip()
	}

	void downloadAndUnzip() {
		def keycloakVersion = "keycloak-26.1.0"
		def versionFile = new File('build/' + keycloakVersion + '/version.txt');
		if(!versionFile.exists()) {
			def zipFile = new File('build/' + keycloakVersion + '.zip')
			if (!zipFile.exists()) {
				new URL('https://github.com/keycloak/keycloak/releases/download/26.1.0/keycloak-26.1.0.zip')
						.withInputStream { i -> zipFile.withOutputStream { it << i } }
			}

			// unzip
			def outputDir = zipFile.getParent()
			byte[] buffer = new byte[1024]
			ZipInputStream zis = new ZipInputStream(new FileInputStream(zipFile))
			ZipEntry zipEntry = zis.getNextEntry()
			while (zipEntry != null) {
				File newFile = new File(outputDir + File.separator, zipEntry.name)
				if (zipEntry.isDirectory()) {
					if (!newFile.isDirectory() && !newFile.mkdirs()) {
						throw new IOException("Failed to create directory " + newFile)
					}
				} else {
					// fix for Windows-created archives
					File parent = newFile.parentFile
					if (!parent.isDirectory() && !parent.mkdirs()) {
						throw new IOException("Failed to create directory " + parent)
					}
					// write file content
					FileOutputStream fos = new FileOutputStream(newFile)
					int len = 0
					while ((len = zis.read(buffer)) > 0) {
						fos.write(buffer, 0, len)
					}
					fos.close()
				}
				zipEntry = zis.getNextEntry()
			}
			zis.closeEntry()
			zis.close()
		}
	}
}


tasks.register("keycloak", KeycloakTask)